apiVersion: v1
kind: Service
metadata:
  name: shypple-heap-proxy-service
spec:
  selector:
    app: shypple-heap-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP